# COGS 108 - Data Checkpoint

## Authors

- Amrutha Velivelli: Data curation, Software, Writing - review & editing
- Anton Vu: Background research, Conceptualization, Writing - original draft
- Sunehra Pululgurta: Data curation, project administration, methodology  Writing - original draft, review & editing
- Tanisha Varma: Background research, Conceptualization, Writing - original draft
- Mitzi Ramos-Rodriguez: Project administration, software, visualization, Writing - review & editing

## Research Question

Research question: How does the amount of sleep college students get each night relate to their academic performance, and can sleep patterns help predict changes in GPA or course grades?


Independent Variable (Sleep Amount): Average number of hours a college student sleeps per night, measured through self-reported survey responses over a typical school week.

Independent Variable (Sleep Patterns): Consistency of sleep schedule, including average bedtime, wake-up time, and variation in sleep duration between weekdays and weekends.

Dependent Variable (Academic Performance): Student GPA and/or percentage course grades, measured using self-reported cumulative GPA or grades from current courses.

Population: College students enrolled in undergraduate courses.

## Background and Prior Work

Sleep plays an important role in cognitive functioning, learning, memory, and academic success. College students often struggle with inconsistent sleep schedules due to academic pressure, social activities, work responsibilities, and technology use. These irregular sleep habits can negatively affect concentration, motivation, and overall classroom performance. Because of this, researchers have spent years studying the relationship between sleep and academic achievement among college students.

Previous research has consistently shown a strong connection between sleep quality and academic performance. In a study conducted by Gilbert and Weaver, researchers surveyed university students about their sleep habits and compared the results to their grade point averages (GPA). The study found that students with poorer sleep quality and greater daytime sleepiness tended to have lower GPAs (Gilbert & Weaver, 2010). Their findings suggested that not only the amount of sleep, but also the quality of sleep, plays an important role in academic success. However, the study relied heavily on self-reported data, which may reduce accuracy because students may incorrectly estimate their sleep patterns or academic behaviors.
Similarly, Curcio, Ferrara, and De Gennaro (2006) conducted a large review of previous studies examining the effects of sleep deprivation on learning and academic performance. Their review analyzed evidence from multiple experiments and concluded that sleep loss negatively impacts attention span, memory consolidation, problem-solving skills, and the ability to learn new information. The researchers explained that students who consistently lose sleep may struggle to retain information learned in class, which can lead to lower academic performance over time (Curcio et al., 2006). One limitation of this review is that many of the studies included different age groups and research methods, making it difficult to generalize the results specifically to college students.

In addition, Hershner and Chervin (2014) examined the causes and consequences of sleep deprivation among college students. Their research reviewed common factors that contribute to poor sleep, including stress, heavy coursework, electronic device use, and irregular schedules. The study found that insufficient sleep was linked to reduced alertness, impaired learning, poorer academic performance, and increased mental health concerns among college students (Hershner & Chervin, 2014). The researchers also emphasized that many students underestimate the importance of sleep and fail to recognize how sleep deprivation affects their daily functioning. While the study provided a broad overview of sleep-related issues, it focused more on general consequences of sleep deprivation rather than predicting specific changes in GPA or course grades.
Overall, past research strongly supports the idea that sleep affects how well students perform academically. Prior studies show that poor sleep quality and sleep deprivation are associated with lower GPA, reduced learning ability, and weaker academic outcomes. However, many studies rely on self-reported sleep data or focus broadly on academic performance rather than predicting specific changes in GPA or course grades over time. These limitations help support the purpose of this project, which aims to further examine whether sleep patterns can help predict academic performance among college students.

References
Gilbert, S. P., & Weaver, C. C. (2010). Sleep quality and academic performance in university students. College Student Journal, 44(2), 295–303.
Curcio, G., Ferrara, M., & De Gennaro, L. (2006). Sleep loss, learning capacity and academic performance. Sleep Medicine Reviews, 10(5), 323–337.
Hershner, S., & Chervin, R. (2014). Causes and consequences of sleepiness among college students. Nature and Science of Sleep, 6, 73–84.

## Hypothesis

Students who obtain longer and more consistent sleep will achieve higher GPAs and course grades compared to students with shorter or irregular sleep patterns.

Additionally, we hypothesize that improvements in sleep duration and consistency over time will predict measurable improvements in academic performance.

This hypothesis is grounded in prior research showing that sleep enhances memory consolidation, attention, and executive functioning—all of which are critical for learning and academic success.

## Data

### Data overview

Dataset #1
  - Dataset Name: Nightly sleep time and GPA in first-years
  - Link to the dataset: https://cmustatistics.github.io/data-repository/psychology/cmu-sleep.html#data
  - Number of observations: 634
  - Number of variables: 15
  
Variables:
  - TotalSleepTime — average amount of sleep each student gets
  - bedtime_mssd — variability in bedtime schedules
  - midpoint_sleep — midpoint of sleep timing
  - daytime_sleep — amount of daytime sleep or napping
  - cum_gpa — cumulative GPA
  - term_gpa — GPA for the current term
  - demographic variables such as gender, race, and first-generation college student status

These variables are useful for studying whether sleep duration, consistency, and sleep timing are related to academic performance in first-year college students.

One limitation is that the dataset focuses only on first-year college students from a few universities, so the results may not generalize to all populations. In addition, some variables contain missing values, and sleep data may vary due to stress, schedules, or lifestyle factors not fully captured in the dataset. The dataset also mainly shows correlations and cannot prove causation between sleep and GPA.

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [3]:
import os
import shutil

# Create raw data folder if it doesn't exist
os.makedirs('data/00-raw/', exist_ok=True)

# Copy uploaded CSV into raw data folder
shutil.copy('cmu-sleep.csv', 'data/00-raw/cmu-sleep.csv')

print("Dataset copied successfully.")

Dataset copied successfully.

In [14]:
import pandas as pd

sleep = pd.read_csv('data/00-raw/cmu-sleep.csv')

sleep.head()

,subject_id,study,cohort,demo_race,demo_gender,demo_firstgen,bedtime_mssd,TotalSleepTime,midpoint_sleep,frac_nights_with_data,daytime_sleep,cum_gpa,term_gpa,term_units,Zterm_units_ZofZ
0,185,5,lac1,1,1,0,0.116727,432.200000,458.660000,0.862069,24.160000,3.00,3.38,73,4.055294859
1,158,5,lac1,0,1,0,0.141681,391.931035,364.465517,1.000000,13.137931,3.66,2.60,64,2.482534122
2,209,5,lac1,1,1,0,1.529289,344.304348,560.891304,0.793103,14.956522,3.57,3.07,63,2.30778293
3,102,5,lac1,0,1,1,0.130148,392.620690,416.482759,1.000000,54.551724,3.61,3.56,61,1.958280544
4,174,5,lac1,1,1,0,0.130181,423.421053,368.763158,0.655172,10.526316,3.21,4.00,61,1.958280544

### CMU Sleep and Psychology Dataset 

The primary dataset used in this project is the CMU Sleep and Psychology Dataset, available through the CMU Statistics Data Repository. This dataset contains information related to sleep behaviors, stress, caffeine consumption, and measures of cognitive or academic functioning. The dataset includes over 600 participant observations and multiple variables that capture different aspects of sleep and psychological well-being. Each row in the dataset represents an individual participant, while each column represents a measured variable, making the dataset relatively tidy and straightforward to analyze.

Several variables in the dataset are especially important for this project. Sleep Duration measures the number of hours participants sleep each night and is useful for examining whether insufficient sleep is associated with reduced cognitive performance or increased fatigue. Sleep Quality provides a subjective measure of how restful participants perceive their sleep to be, which may be just as important as total sleep time. The dataset also includes variables related to Stress Levels, which can influence both sleep habits and academic functioning, and Caffeine Consumption, which may temporarily improve alertness while also disrupting long-term sleep quality. Additional variables measuring daytime tiredness, fatigue, or performance outcomes help provide insight into how sleep behaviors affect daily functioning.

This dataset has several limitations that are important to consider. Most of the information is self-reported, meaning participants may unintentionally misreport their sleep habits, stress levels, or caffeine intake. The sample may also be biased because participants were likely students or volunteers interested in psychology or health research, which may not accurately represent the broader population. In addition, sleep patterns among college students are often influenced by irregular schedules, academic pressure, and social activities, making the findings less generalizable to non-student groups. The dataset may also contain missing values or outliers, such as unusually low sleep durations or extremely high caffeine consumption, which will need to be examined and cleaned during preprocessing.

3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [10]:

import pandas as pd
import os

sleep = pd.read_csv('data/00-raw/cmu-sleep.csv')

sleep.head()


print("Dataset shape:")
print(sleep.shape)


print("\nColumn names:")
print(sleep.columns)



print("\nMissing values:")
print(sleep.isnull().sum())


print("\nSummary statistics:")
sleep.describe()

print("\nMinimum values:")
print(sleep.min(numeric_only=True))

print("\nMaximum values:")
print(sleep.max(numeric_only=True))



sleep_clean = sleep.dropna(how='all')


sleep_clean = sleep_clean.fillna(
    sleep_clean.median(numeric_only=True)
)



os.makedirs('data/02-processed', exist_ok=True)

sleep_clean.to_csv(
    'data/02-processed/cmu_sleep_clean.csv',
    index=False
)
print("\nCleaned dataset preview:")

display(sleep_clean.head())

Dataset shape:
(634, 15)

Column names:
Index(['subject_id', 'study', 'cohort', 'demo_race', 'demo_gender',
       'demo_firstgen', 'bedtime_mssd', 'TotalSleepTime', 'midpoint_sleep',
       'frac_nights_with_data', 'daytime_sleep', 'cum_gpa', 'term_gpa',
       'term_units', 'Zterm_units_ZofZ'],
      dtype='object')

Missing values:
subject_id               0
study                    0
cohort                   0
demo_race                0
demo_gender              0
demo_firstgen            0
bedtime_mssd             0
TotalSleepTime           0
midpoint_sleep           0
frac_nights_with_data    0
daytime_sleep            0
cum_gpa                  0
term_gpa                 0
term_units               0
Zterm_units_ZofZ         0
dtype: int64

Summary statistics:

Minimum values:
subject_id                 1.000000
study                      1.000000
bedtime_mssd               0.004505
TotalSleepTime           194.782609
midpoint_sleep           247.071429
frac_nights_with_data      0.214286
daytime_sleep              2.269231
cum_gpa                    1.210000
term_gpa                   0.350000
dtype: float64

Maximum values:
subject_id               99978.000000
study                        5.000000
bedtime_mssd                20.849225
TotalSleepTime             587.666667
midpoint_sleep             724.666667
frac_nights_with_data        1.000000
daytime_sleep              292.304348
cum_gpa                      4.000000
term_gpa                     4.000000
dtype: float64

Cleaned dataset preview:

,subject_id,study,cohort,demo_race,demo_gender,demo_firstgen,bedtime_mssd,TotalSleepTime,midpoint_sleep,frac_nights_with_data,daytime_sleep,cum_gpa,term_gpa,term_units,Zterm_units_ZofZ
0,185,5,lac1,1,1,0,0.116727,432.200000,458.660000,0.862069,24.160000,3.00,3.38,73,4.055294859
1,158,5,lac1,0,1,0,0.141681,391.931035,364.465517,1.000000,13.137931,3.66,2.60,64,2.482534122
2,209,5,lac1,1,1,0,1.529289,344.304348,560.891304,0.793103,14.956522,3.57,3.07,63,2.30778293
3,102,5,lac1,0,1,1,0.130148,392.620690,416.482759,1.000000,54.551724,3.61,3.56,61,1.958280544
4,174,5,lac1,1,1,0,0.130181,423.421053,368.763158,0.655172,10.526316,3.21,4.00,61,1.958280544

## Ethics

Data Collection

- Informed consent: Students must voluntarily agree to share their sleep and academic data and be clearly informed about how the data will be collected, used, and stored.
- Collection bias: Participation may be biased toward certain groups (e.g., more motivated or health-conscious students), which could limit how representative the dataset is.
- Limit PII exposure: Personally identifiable information (such as names, student IDs, or emails) will not be collected, or will be removed during preprocessing to protect participant privacy.

Data Storage

- Data security: All data will be stored in secure, access-controlled environments (e.g., password-protected systems or approved cloud storage).
- Right to be forgotten: Participants will have the ability to request that their data be removed from the dataset at any time.
- Data retention plan: Data will only be stored for the duration of the project and will be deleted after completion to minimize long-term risk.

Analysis

- Missing perspectives: The dataset may not capture all factors that influence academic performance (e.g., mental health, socioeconomic status), so conclusions will be made cautiously.
- Dataset bias: We will evaluate whether certain demographic groups are underrepresented and discuss how this may affect the validity and generalizability of results.
- Honest representation: Visualizations and statistical summaries will accurately reflect the data without exaggerating trends or implying causation where only correlation exists.
- Privacy in analysis: Results will only be presented in aggregate form, ensuring that no individual student can be identified.
- Auditability: All data processing and analysis steps will be documented and reproducible, allowing others to verify results.

## Team Expectations

- Communicate clearly and respectfully through the group’s chosen platform.
- Attend meetings or let the team know ahead of time if you can’t.
- Finish assigned tasks on time and put in your best effort.
- Be open to feedback and willing to revise your work.
- Support each other and maintain a positive working environment.
- Handle disagreements calmly and respectfully, involving the TA if necessary.

## Project Timeline Proposal

| Meeting Date | Meeting Time | Completed Before Meeting | Discuss at Meeting |
|---|---|---|---|
| 4/29 | TBD | Review COGS 108 expectations; brainstorm project ideas; begin preliminary background research | Decide communication methods; narrow project topic; refine research question and hypothesis |
| 5/6 | TBD | Finalize background research; define variables; identify datasets; complete proposal draft | Discuss dataset quality and ethics; plan wrangling approach; assign analysis responsibilities |
| 5/13 | TBD | Import dataset(s); begin cleaning and preprocessing | Review wrangling progress; troubleshoot issues; refine analysis workflow |
| 5/20 | TBD | Finish data wrangling; begin exploratory data analysis (EDA) | Discuss EDA findings; identify trends and possible adjustments |
| 5/27 | TBD | Continue EDA; start statistical testing or modeling | Review preliminary results; refine methods and interpretation |
| 6/3 | TBD | Complete analysis; draft results and conclusion sections | Review complete draft; provide edits and feedback |
| 6/10 | TBD | Final formatting, visualizations, and proofreading | Final project check-in; prepare submission materials |
| Final Deadline | Before 11:59 PM | N/A | Submit Final Project & Group Surveys |